### ISSUE TITLE
feat: add support for Facebook Recommendations

### ISSUE THREAD

**Issue by mathetos** [impress-org/wp-business-reviews#246]
A lot of things are changing with Facebook Pages, and we need to get ahead of it, and it's a little troublesome because it might impact our connect app. Here's a quick list of things we need to research and be ready for:

- [x] *Ratings are Going Away* 
See here: https://www.facebook.com/business/recommendations 
Here's a blog post about it: https://www.reshiftmedia.com/facebook-moves-away-from-star-ratings-in-favour-of-recommendations/

- [x] *Recommedations are the new Ratings*
If this is true, then we'd need to make sure we can pull in the new Recommendations, instead of the Ratings. Currently on our WPBR page, we have one Rating (from bet hannon) and one Recommendation (Roy Sivan), and that means that currently in the plugin BOTH are being pulled in, but the Recommendation shows ZERO stars.
![image](https://user-images.githubusercontent.com/930724/44867229-17ac8e80-ac3c-11e8-9da5-6c26f74070bd.png)

- [x] Business Pages will have their own Ratings, seperate from Recommendations, based on a undisclosed algorithm. 
See here: https://www.socialmediatoday.com/news/facebook-tests-new-rating-system-for-brand-pages/523505/

We need to research what this looks at from an API perspective and create issues to address these new developments.

**Comment by kevinwhoffman** [comment]
For now, Facebook users are still able to leave star ratings in addition to recommendations, so we need to handle both.

Regarding API changes, here's what I found:

> Beginning August 17, 2018 we are introducing a new ratings parameter that captures recommendations, recommendation_type with values of positive or negative. This new parameter is replacing the rating parameter with its 1 to 5 scale. Ratings created after August 13 will use this new parameter.

## Acceptance Criteria

- [ ] Do not show empty stars if a numeric rating does not exist. This means even if `Star Rating` is checked in the collection settings, we only show it if there is actually a rating greater than 0.
- [ ] Handle `positive` and `negative` recommendations in the review filters. If I set the minimum rating to 5 stars, it's only going to show reviews with `5` rating, but the user probably expects positive recommendations to stay visible, too.

**Comment by DevinWalker** [comment]
Rather than removing the stars completely, I'd rather see something like this in their place should it be a positive recommendation:

![2018-09-04_12-01-17](https://user-images.githubusercontent.com/1571635/45051997-7443eb00-b03a-11e8-935e-9ecb8b58258c.png)

**Comment by kevinwhoffman** [comment]
Good idea. The red star bubble is Facebook's icon used for recommendations.

![image](https://user-images.githubusercontent.com/1938671/45052219-2d62ef00-b054-11e8-94b9-e010ed2ffae5.png)

How about this?

![image](https://user-images.githubusercontent.com/1938671/45052705-c3e3e000-b055-11e8-8e21-40dc270e18b5.png)

**Comment by mathetos** [comment]
What about the wording "Recommends [business page name]"?

We will also need a "Does not recommend" since they will come over the API as well.

**Comment by telizarose** [comment]
It looks like Facebook recommendations show up the same whether or not they were recommended. Here is an image with a clearly negative comment on a rec and a clearly positive one. Both have 0 stars. 

<img width="788" alt="screen shot 2018-09-06 at 8 00 02 am" src="https://user-images.githubusercontent.com/38927530/45166040-f521f480-b1aa-11e8-8e35-a81479d0bd9c.png">

**Comment by kevinwhoffman** [comment]
@telizarose The reason positive and negative recommendations look the same right now is because the plugin is only looking for a star rating. Once I add the logic to detect recommendations, we can display them accordingly.

-----

Here's what I'm thinking based on Facebook's usage of the red/gray star bubbles in recommendations.

## Positive Recommendation

![recommends](https://user-images.githubusercontent.com/1938671/45186970-3511c780-b1fd-11e8-934b-32be65f3e0c2.jpg)

## Negative Recommendation

![does-not-recommend](https://user-images.githubusercontent.com/1938671/45186973-37742180-b1fd-11e8-801d-7a4cc2bb25ae.jpg)

-----

> What about the wording "Recommends [business page name]"?

@mathetos I was initially worried this would create wrapping issues, but I think we can keep it to one line and truncate based on the space available using `text-overflow: ellipsis;`. This is how Facebook does it, and I think we can do the same. See the negative recommendation above for an example.

**Comment by DevinWalker** [comment]
Looks good to me!

**Comment by mathetos** [comment]
I like it.

**Comment by kevinwhoffman** [comment]
To clarify the differences between a Review and a Recommendation in terms of the API response:

- Recommendations include `recommendation_type` but not `rating`.
- Reviews include both `recommendation_type` and `rating`.

This means in order to determine if a post is a recommendation, we should first assume it's a Review and check for the presence of a `rating` field. If `rating` does not exist then assume it is a recommendation and fall back to `recommendation_type` to determine red/gray bubble. If neither exists, do not display anything on that line (this should never happen but will at least prevent empty star ratings if it does).

![image](https://user-images.githubusercontent.com/1938671/45835705-cc384e00-bcd8-11e8-84d7-4909812aa309.png)

**Comment by kevinwhoffman** [comment]
## Status Update

- [x] Detect and save `recommendation_type` as `wpbr_rating` term if a numerical rating does not exist.
- [x] Style recommendation with red/gray bubble icons.
- [x] Add JS logic to determine star rating vs. recommendation.
- [ ] Add `review_source_name` as a review component so that it is available for recommendation text.
- [ ] Add conditional control to single review editor so user can define whether review is rating or recommendation. This will allow users to update existing reviews with missing recommendation types.
