### ISSUE TITLE
fix: prevent error caused by date format in single reviews

### ISSUE THREAD

**Issue by mathetos** [impress-org/wp-business-reviews#251]
## Steps to Replicate:
1. Go to "Settings > General"
2. Change your Day Format to be `d/m/Y`
3. Go to create a Single Review and choose a date.
4. Upon Save you'll get the following fatal error:
`Fatal error: Uncaught Exception: DateTime::__construct(): Failed to parse time string (19/09/2018) at position 0 (1): Unexpected character in /app/public/wp-content/plugins/wp-business-reviews/includes/serializer/class-review-serializer.php on line 136`

## Related:
* https://secure.helpscout.net/conversation/657965972/24954?folderId=2120001
* https://github.com/WordImpress/wp-business-reviews/issues/240

# Acceptance Criteria

- [x] A single review can be saved with any date format including default WP date formats or completely custom formats.
- [x] A single review can be saved when the site language is changed to a non-English language.
- [x] The datepicker reflects the localized date format from WP settings.
- [x] The hidden alternative field for the datepicker is always formatted as `yyyy-mm-dd`.

**Comment by kevinwhoffman** [comment]
This is related to https://github.com/WordImpress/wp-business-reviews/issues/240 but we can probably fix the fatal error without having to solve all of #240 so I think we can get this into 1.0.2.

**Comment by mathetos** [comment]
This error is still happening on Single Reviews when the date format is `j. F Y` -- which is the default date format in Germany and most likely other European countries.

**Comment by kevinwhoffman** [comment]
I will test against this `j. F Y` format and try to resolve.

**Comment by kevinwhoffman** [comment]
Update: When saving single reviews, the `j. F Y` format worked fine as a custom format with `English (United States)` site language. However I was able to replicate the error once I changed the site language to `Deutsch`.

The cause of the error is not any specific format, but rather any format that includes translated words as opposed to numbers. For example, I replicated the error on a `Deutch` site using both `j. F Y` and  `F j, Y` formats, whereas `m/d/Y` worked fine because it did not include a translated word like `Oktober`.

I will make sure date formats with translated strings work as expected.

**Comment by kevinwhoffman** [comment]
Update: I am implementing `altField` and `altFormat` options that are available in the jQuery datepicker. This way we can submit a separate, hidden input with a predictable format while allowing the datepicker to still display the localized version.

- https://stackoverflow.com/a/13958379
- https://api.jqueryui.com/datepicker/#option-altField
